---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chinrlfh/cinarli-app/
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp next.config.mjs $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH